services:
  simulation:
    image: simulation:latest
    build:
      context: .
      dockerfile: docker/singlestage.Dockerfile
      # The entrypoint script handles the runtime matching regardless.
      args:
        # expect there to be either a .env or suitable env vars
        USER_UID: ${UID}
        USER_GID: ${GID}
    volumes:
      # Named volume for the virtual environment persistence
      - sim_venv:/sim/venv
      # Named volume for persistent simulation data (compiled network, trajectory.txt...)
      - sim_shared_data:/sim/shared_data
      # Named volume for nest modules (so that user-generated ones are persisted)
      - nest_module_path:/sim/install/nest/lib/nest/
      # Bind mount the current host directory (.) into /sim/controller
      - .:/sim/controller
    stdin_open: true
    tty: true
    environment:
      TZ: ${TZ:-Europe/Rome}
      VNC_PASSWORD: ${VNC_PASSWORD} # this is not a secret.
    ports:
      # Map host port 5901 (localhost only) to container port 5901 (VNC display :1)
      - "127.0.0.1:5901:5901"
    # If you want to run a specific script, use 'docker-compose run simulation python your_script.py'
    command: bash

volumes:
  sim_venv:
  sim_shared_data:
  nest_module_path: